### ISSUE TITLE
How to configure wal-g backup?

### ISSUE THREAD

**Issue by Jamic28** [vitabaks/autobase#819]
How to configure wal-g backup:
1. Full backup every 2 days at evening 01:01?
2. Delta backups every 10 minutes?

**Comment by vitabaks** [comment]
I don’t think performing Delta backups every 10 minutes makes sense, especially for large databases. Instead, we can rely on WAL archiving with the `archive_timeout='600s'` option (10 minutes).

As for Full backups, I typically recommend scheduling them once a week, with Delta backups performed daily. This approach balances backup frequency with resource usage while ensuring recoverability.

**Comment by vitabaks** [comment]
There are other effective DR strategies with lower RPO/RTO. To provide more precise recommendations, we would need more details about your service.

We encourage you to explore our[ individual support packages](https://postgresql-cluster.org/docs/support#commercial-support) for tailored guidance.

**Comment by Jamic28** [comment]
> As for Full backups, I typically recommend scheduling them once a week, with Delta backups performed daily. This approach balances backup frequency with resource usage while ensuring recoverability.

Thanks @vitabaks! Is this scheduling configuration is correct for once full backup a week, with daily Delta backups ?
>  - { option: "WALG_DELTA_MAX_STEPS", value: "{{ WALG_DELTA_MAX_STEPS | default('7') }}" } 
...
>wal_g_cron_jobs:
  - name: "WAL-G: Create daily backup"
    user: "postgres"
    file: /etc/cron.d/walg
    minute: "0"
    hour: "{{ WALG_BACKUP_HOUR | default('3') }}"
    day: "*"
    month: "*"
    weekday: "0"
    job: "{{ wal_g_backup_command | join('') }}"

It is not clear how to create daily Delta backups?

**Comment by Jamic28** [comment]
>wal_g_cron_jobs:
  - name: "WAL-G: Create daily delta backup"
    user: "postgres"
    file: /etc/cron.d/walg_delta
    minute: "0"
    hour: "3"
    day: "*"
    month: "*"
    weekday: "*"
    job: "{{ wal_g_backup_command | join('') }} --delta"
  - name: "WAL-G: Create weekly full backup"
    user: "postgres"
    file: /etc/cron.d/walg_full
    minute: "0"
    hour: "3"
    day: "*"
    month: "*"
    weekday: "0"
    job: "{{ wal_g_backup_command | join('') }} --full"

Will this ansible config work?

**Comment by Jamic28** [comment]
>wal_g_cron_jobs:
  - name: "WAL-G: Create daily delta backup"
    user: "postgres"
    file: /etc/cron.d/walg_delta
    minute: "0"
    hour: "1"
    day: "*"
    month: "*"
    weekday: "*"
    job: "{{ wal_g_backup_command | join('') }} --delta-from-name LATEST"
  - name: "WAL-G: Create weekly full backup"
    user: "postgres"
    file: /etc/cron.d/walg_full
    minute: "0"
    hour: "1"
    day: "*"
    month: "*"
    weekday: "0"
    job: "{{ wal_g_backup_command | join('') }} --full"

Will this config work if I add it to the ansible playbook?

**Comment by vitabaks** [comment]
Yes, see configuration examples: https://autobase.tech/docs/management/backup#command-line

**Comment by vitabaks** [comment]
> It is not clear how to create daily Delta backups?

WAL-G automatically creates a full backup and subsequent backups as incremental, based on the configuration set by the **`WALG_DELTA_MAX_STEPS`** parameter. This parameter defines the maximum number of incremental backups allowed between full backups.

**Comment by Jamic28** [comment]
If we configure full backup once a week, then in order for delta backups to be once a day it should be 7?
"WALG_DELTA_MAX_STEPS", value: "7"

**Comment by vitabaks** [comment]
If you configure a full backup to occur once a week and want delta backups to occur daily, you should set `WALG_DELTA_MAX_STEPS` to `6`. Here's why:

- Full Backup: Happens once a week (e.g., every 7 days).
- Delta Backups: Occur daily between full backups.

The WALG_DELTA_MAX_STEPS parameter defines the maximum number of incremental backups (delta) that can be created before a new full backup is forced. If you want 6 delta backups (one for each day before the next full backup), then WALG_DELTA_MAX_STEPS should be 6.

**Comment by Jamic28** [comment]
Thanks!
