### ISSUE TITLE
NOOB Question: How To Connect to Cluster (Hetzner)?

### ISSUE THREAD

**Issue by nelsonic** [vitabaks/autobase#824]
Hi @vitabaks, 👋 
We've deployed a `Postgres` cluster to `Hetzner` using `autobase`. 🚀 
Following your docs: https://autobase.tech/docs/deployment/hetzner 📖 👌 
(good work on the re-brand BTW 😉)

<img width="1273" alt="autobase-cluster" src="https://github.com/user-attachments/assets/28bef6f6-dcce-4be5-bb7e-45334e3e1019">

But it's unclear how to connect to the cluster ... 🤷‍♂️ 
It doesn't _appear_ as though there is a single entry point (load balancer). 🤔 

These are the servers:
<img width="1475" alt="image" src="https://github.com/user-attachments/assets/78a0786c-f73c-4fdd-ba1c-abed29b4d7d4">

And load balancers:

<img width="1475" alt="image" src="https://github.com/user-attachments/assets/3a1693ac-ccde-4876-bfff-5a3f308b883e">

But they say "**Public network is disabled**" when we hover over the IP:
<img width="558" alt="image" src="https://github.com/user-attachments/assets/fcc75abf-7867-423a-96cd-29e6fd2e2917">

So it's unclear how to connect ... 

Reading the docs: https://autobase.tech/docs/management/basic-commands#postgresql
<img width="1403" alt="image" src="https://github.com/user-attachments/assets/2e48367b-76d7-4e06-9796-b81d1a9ce07f">

We _can_ connect to `Postgres` by `ssh`-ing into the VM e.g: 
<img width="1117" alt="image" src="https://github.com/user-attachments/assets/d477053c-9275-4c15-acac-ece27795d709">

```sh
ssh root@88.99.81.115
```

And run the command (from your docs):

```sh
psql -h 127.0.0.1 -p 5432 -U postgres -d postgres -c "select version()"
```

We get the following output:

<img width="965" alt="image" src="https://github.com/user-attachments/assets/c1a243d1-64bf-4963-a3fc-bb449c75352e">

But obvs we don't want to have to `ssh` into a VM to connect to the `Postgres` DB on it ...

If we `ssh` into the VM that has the `autobase` console running on it:

<img width="914" alt="image" src="https://github.com/user-attachments/assets/b398681d-c826-4538-bdb0-a532c003c6d0">

```sh
ssh root@116.202.31.52
```

and then attempt to connect to one of the VM/nodes that was deployed/configured by `autobase`:

```sh
export PGPASSWORD='thepasswordinconfig';
psql -h 10.0.1.1 -p 5432 -U postgres -d postgres
```

Same for attempting to connect via the `loadbalancer` internal IP:

```sh
export PGPASSWORD='thepasswordinconfig';
psql -h 10.0.1.4 -p 6432 -U postgres -d postgres
```

Both just hang and time-out:

<img width="1193" alt="image" src="https://github.com/user-attachments/assets/f9d6e616-3062-4d5b-a48c-22657df56de6">

Have tried all combinations of IP address (public/internal) & Port Number and no result. 

What am I doing wrong? 🤷‍♂️ 
Any help much appreciated. Thanks! 🙏

**Comment by vitabaks** [comment]
Hi @nelsonic 

> good work on the re-brand BTW

Thanks!

Our solution is configured by default for production environment, which is why public access is disabled by default. To connect to the database, your application must be on the same network as the database cluster.

If you require access to the database from the internet, simply enable public access in the load balancer settings.

**Comment by vitabaks** [comment]
In a future version, the ability to configure public access will be added in the UI - https://github.com/vitabaks/autobase/issues/756

![image](https://github.com/user-attachments/assets/458bd6e1-69e1-4ee8-b78f-f1ad4ed219cb)

**Comment by nelsonic** [comment]
Yeah, wasn't expecting the cluster to be publicly accessible ... 
Just trying to access from within the same `private` network. 

But looking at the `hetzner` **Networks** page it appears there are _two_ Networks:
<img width="1422" alt="image" src="https://github.com/user-attachments/assets/71adc36e-e27d-46e8-b2ba-2ee8a89ffc9b">

One which I had created when deploying the initial VM to run the `autobase` console:

<img width="1299" alt="image" src="https://github.com/user-attachments/assets/6c1500a1-6196-417f-a740-89781e0293d9">

And the other that was created _by_ `autobase` for the cluster:

<img width="1421" alt="image" src="https://github.com/user-attachments/assets/3d3818d1-cad7-4784-9a13-ae758db08491">


I detached the original server from the `private-network`:

<img width="1299" alt="image" src="https://github.com/user-attachments/assets/7cabcec0-e97d-4b04-8666-3fa226507119">

<img width="1299" alt="image" src="https://github.com/user-attachments/assets/47ddc50a-dcd5-4f75-bf7e-cc3d2324599c">

And then _deleted_ the no longer needed network:

<img width="1299" alt="image" src="https://github.com/user-attachments/assets/0d43e6da-f80b-43a9-aa81-8d55d8d087d3">

Now there is only _one_ network:
<img width="1299" alt="image" src="https://github.com/user-attachments/assets/54bb39bc-1087-4af8-9200-0218b49d45e2">

Detail:
<img width="1309" alt="image" src="https://github.com/user-attachments/assets/585c0940-02b2-4580-bdf6-834702c704ff">

Attached the VM to the `postgres-cluster-network-eu-central` Network:

<img width="1309" alt="image" src="https://github.com/user-attachments/assets/2c178660-dd9b-42ce-ad37-43a6ad0885b3">

Now there are 6 resources in the net:
<img width="1309" alt="image" src="https://github.com/user-attachments/assets/e4d26b33-8851-4c4b-a4cd-7ff114631a43">


And now we can connect!! 

```sh
psql -h 10.0.1.4 -p 6432 -U postgres -d postgres -c "select version()"
```

<img width="1265" alt="image" src="https://github.com/user-attachments/assets/76e73378-83d7-43f5-b8c7-03b10f8ea407">

**Comment by vitabaks** [comment]
Great! I’m glad to hear that you can now connect to the database for bathhouses. Next, just make sure to place the application servers on the same network.

We also plan to add the ability to specify the name of an existing network directly in the UI.
