### ISSUE TITLE
Why is `Hetzner` default instance `CPX11` instead of `CX22`? 💭 

### ISSUE THREAD

**Issue by nelsonic** [vitabaks/autobase#834]
G'Morning @vitabaks 👋,
Hope this message finds you well. 👌 

Busy setting up a `Postgres` cluster using `autobase` 🫶 
Noticing that the default instance type is `CPX11` and no way to switch to a more cost effective instance type...

<img width="1836" alt="image" src="https://github.com/user-attachments/assets/f745d5de-abe8-45ad-8727-51a6d4b160cd">

The `CPX11` instance type has only `2 GB RAM` + `2 vCPU` and costs `€3.85/month` 

<img width="1115" alt="image" src="https://github.com/user-attachments/assets/04330eb3-cf14-40a1-9a4e-d6b7ffe76bc8">

The `CX22` has `4 GB RAM` (the same `2 vCPU`) and is _cheaper_ (`€3.29`) per month:
<img width="1112" alt="image" src="https://github.com/user-attachments/assets/24d3c19c-f343-4e60-a27e-324ac25d95bb">

Ref: https://www.hetzner.com/cloud/

<img width="1436" alt="hetzner-CX22-instance-cheaper" src="https://github.com/user-attachments/assets/db0cb481-7f8b-4a84-870e-d8ec7e6604d4">

would be good to get some clarity on why the `cpx11` instance type is the `default`. 🤷‍♂️ 
and if there's no strong reason for it, would you accept a PR allowing people to select the `CX22`?

Note: there is a `Reddit` thread explaining the difference in instance type; 
One uses `Intel` CPU whereas the other uses `AMD` 🧠 

https://www.reddit.com/r/hetzner/comments/1gwggv8/cx22_vs_cpx11/ 🔗 
<img width="748" alt="image" src="https://github.com/user-attachments/assets/2e3c70b7-0f29-420c-84aa-b7af73fca6bd">

I'd argue that having _double_ the `RAM` to store more data in-memory and cache queries results 
has a bigger advantage than a marginally faster processor. 
But _you_ sir, are the `Postgres` Expert, so I defer to your experience. 🙏 

Thanks. 👌 

> **Note**: using the `default` `CPX11` instance type  for the screencast I'm working on _for now_ ... 📺 
> But would _prefer_ to use `CX22` for our actual servers where `RAM` is more important than an `AMD` CPU.

**Comment by vitabaks** [comment]
Hi @nelsonic 

The CPX11 is a shared CPU instance, added specifically for testing purposes. For production, we recommend using dedicated CPU instances, which is why they are the only ones listed by default. 

However, if needed, you can manually add the instance types you require to the console database in the [cloud_instances](https://github.com/vitabaks/autobase/blob/2.0.0/console/db/migrations/20240520144338_2.0.0_initial_scheme_setup.sql#L217) table.

Related https://github.com/vitabaks/autobase/issues/784

**Comment by nelsonic** [comment]
Totally agree that a `prod` cluster should be `Dedicated CPU`. 🏎️ 👌 
But for a `hobby` or `test` cluster, price is king. 🤑 

<img width="1345" alt="image" src="https://github.com/user-attachments/assets/48ee27e2-cc59-4fdc-a924-684094dcd370">

For `prod` we will be running _fully_ `Dedicated` resources:
https://www.hetzner.com/dedicated-rootserver/matrix-ax/
<img width="1311" alt="image" src="https://github.com/user-attachments/assets/426ab68f-335f-4cb1-ba81-ee5d90ba3ba8">

e.g: `AX41-NVMe`: https://www.hetzner.com/dedicated-rootserver/ax41-nvme
<img width="1138" alt="image" src="https://github.com/user-attachments/assets/3e680f2f-0399-492c-9726-78bbded402d8">

Which we will deploy via the "Your Machines" option:

<img width="845" alt="image" src="https://github.com/user-attachments/assets/5dc04cef-dde5-4ea8-8fa1-1e158327439b">

But this is a more advanced usecase so, for now, we just want the baseline for our deployment tutorial/screencast. 😉 

Line to be added:

```sql
('hetzner', 'Small Size', 'CX22', 2, 4, 0.0052, 3.29, '€', '2024-12-09'),
```

PR: https://github.com/vitabaks/autobase/pull/835 :shipit:

**Comment by vitabaks** [comment]
I get you, it makes sense.

**Comment by nelsonic** [comment]
The `CPX11` and `CPX21` instance types are both _shared_ vCPU just that they are `AMD` and therefore more expensive:

https://github.com/vitabaks/autobase/blob/03157f74a5b0e10cc992142515cab7f784ac6afc/console/db/migrations/20240520144338_2.0.0_initial_scheme_setup.sql#L295-L296

https://www.hetzner.com/cloud/
<img width="1468" alt="image" src="https://github.com/user-attachments/assets/3ad5ffee-95e6-49d6-b757-9ef80daac6e6">

As suggested by @schonert in https://github.com/vitabaks/autobase/pull/835#issuecomment-2528263028, it makes sense to list the instance pricing in `USD` to aid comparison to all the bigger (_way more expensive!_) US-centric cloud providers ... 

<img width="1468" alt="image" src="https://github.com/user-attachments/assets/e1696f47-7b24-43f7-9087-91ba84953c06">

With your permission, can I update the migration lines to `USD`?
Won't affect any _current_ users of `v2.0.0` but will help any newer people going forward. 💭

**Comment by nelsonic** [comment]
Updated in https://github.com/vitabaks/autobase/pull/835/files 🤞

**Comment by nelsonic** [comment]
The only storage that is listed in `EUR` is `Hetzner`:

https://github.com/vitabaks/autobase/blob/03157f74a5b0e10cc992142515cab7f784ac6afc/console/db/migrations/20240520144338_2.0.0_initial_scheme_setup.sql#L424

Going to update to `USD` to make comparison between cloud providers easier.

**Comment by nelsonic** [comment]
Added _all_ the Hetzner Cloud instance types via: #835 ✅ 
Also addresses #784 👌
