### ISSUE TITLE
Is it normal to increase pgbouncer_processes ?

### ISSUE THREAD

**Issue by algoritmsystems** [vitabaks/autobase#839]
My configuration is
```
...
  - { option: "max_connections", value: "500" }
...
pgbouncer_processes: 4
pgbouncer_max_client_conn: 5000
pgbouncer_max_db_connections: 450
pgbouncer_query_wait_timeout: 120
pgbouncer_default_pool_size: 100
pgbouncer_reserve_pool_size: 20
pgbouncer_default_pool_mode: "transaction"
...
```
Is it normal practice to increase pgbouncer_processes ?
Or it is not recomended to do so in prodaction env?
number of cpu:48

**Comment by vitabaks** [comment]
Hi @algoritmsystems 

This approach is beneficial under heavy loads (e.q., 10K+ TPS), especially when you notice a single CPU core nearing saturation due to the PgBouncer process. \
Adding more PgBouncer processes helps distribute the load across multiple CPU cores, improving performance and scalability.

**Comment by vitabaks** [comment]
Yes, everything is correct, so_reuseport is used.

**Comment by algoritmsystems** [comment]
For postgre max_connections = 1000, by default set
```
pgbouncer_max_client_conn: 100000
pgbouncer_max_db_connections: 10000
```
How to choose the correct value of pgbouncer_max_db_connections in this case? 
It should not exceed max_connections (<1000) in prodaction ?
And will it correct value for pgbouncer_max_client_conn 1000x10 ?

**Comment by vitabaks** [comment]
The default settings are designed to work well for most systems. For customers with specific requirements, we offer personalized configuration recommendations as part of our [support packages](http://autobase.tech/docs/support#commercial-support).

**Comment by algoritmsystems** [comment]
First I set :
`pgbouncer_processes: 4
`
And run deploy_pgcluster
And After change value to 1 and the run with config_pgcluster.  for some reason the pgbouncer processes are not decreasing and all 4 remain:
```
ss -ntlp | grep 6432
LISTEN 0      4096         0.0.0.0:6432      0.0.0.0:*    users:(("pgbouncer",pid=2360837,fd=7))                    
LISTEN 0      4096         0.0.0.0:6432      0.0.0.0:*    users:(("pgbouncer",pid=1625,fd=7))                       
LISTEN 0      4096         0.0.0.0:6432      0.0.0.0:*    users:(("pgbouncer",pid=1623,fd=7))                       
LISTEN 0      4096         0.0.0.0:6432      0.0.0.0:*    users:(("pgbouncer",pid=1621,fd=7))  
```
No cluster restart helps

**Comment by vitabaks** [comment]
Currently it only works to increase processes, but not to decrease them. You can try remove the "extra" manually.

**Comment by Jamic28** [comment]
So I could't reduce the pgbouncer processors. How to remove the "extra" manually? I deleted pgbouncer configs in /etc/pgbouncer/pgbouncer-*.ini files and restart it. but it still there is working one more pgbouncer processors!
